### ISSUE TITLE
coalescelist does not allow all lists to be empty

### ISSUE THREAD

**Issue by nicgordon** [cloudposse/terraform-aws-alb-target-group-cloudwatch-sns-alarms#17]
There was a change in the behaviour of the coalescelist function in terraform 0.12 (see [this issue](https://github.com/hashicorp/terraform/issues/21370)) that means that if you pass it all empty lists it will throw an error. This poses a problem for this module on lines [like this](https://github.com/cloudposse/terraform-aws-alb-target-group-cloudwatch-sns-alarms/blob/master/main.tf#L49) if you are relying on default values.

**Comment by hanswesterbeek** [comment]
Ran into this issue when using https://github.com/cloudposse/terraform-aws-ecs-web-app
