### ISSUE TITLE
module-inputs: alb_arn_suffix and target_group_arn_suffix do not match resource-outputs

### ISSUE THREAD

**Issue by tamsky** [cloudposse/terraform-aws-alb-target-group-cloudwatch-sns-alarms#4]
currently at https://github.com/cloudposse/terraform-aws-alb-target-group-cloudwatch-sns-alarms/blob/master/alarms.tf#L10-L11

we have:
``` tf
    "TargetGroup"  = "${join("/", list("targetgroup", var.target_group_name, var.target_group_arn_suffix))}"
    "LoadBalancer" = "${join("/", list("app", var.alb_name, var.alb_arn_suffix))}"
```

but both of those RHS values (`var.target_group_arn_suffix`, `var.alb_arn_suffix`) already include text that the `join()` statement always adds.

Walking up to this module, I expected to be able to take the resource outputs named `arn_suffix` from both the TG and ALB:
- https://www.terraform.io/docs/providers/aws/r/lb_target_group.html#arn_suffix
- https://www.terraform.io/docs/providers/aws/r/lb.html#arn_suffix

and pass them directly to this module, like this:

``` tf
module "alb_alarms" {
    source                  = "git::https://github.com/cloudposse/terraform-aws-alb-target-group-cloudwatch-sns-alarms.git?ref=tags/0.2.0"
    alb_name          = "${aws_alb.foo.name}"
    alb_arn_suffix          = "${aws_alb.foo.arn_suffix}"
    target_group_name = "${aws_lb_target_group.foo.name}"
    target_group_arn_suffix = "${aws_lb_target_group.foo.arn_suffix}"
...
}
```

Instead, I need to perform the very regex interpolations that the `arn_suffix` resource outputs were specifically designed to eliminate:

``` tf
module "alb_alarms" {
...
    alb_arn_suffix          = "${replace(aws_alb.foo.arn_suffix,"/app/[^/]+//","")}"
    target_group_arn_suffix = "${replace(aws_lb_target_group.foo.arn_suffix,"/targetgroup/[^/]+//","")}"
...
}
```

Is this intentional in this module or am I missing something?

**Comment by tamsky** [comment]
For reference, suffix output examples are in the tests:

- https://github.com/hashicorp/terraform/blob/04bda48c36388593fcb4f5cdb795c4330d9ecc6b/builtin/providers/aws/resource_aws_alb_target_group_test.go#L25
- https://github.com/hashicorp/terraform/blob/04bda48c36388593fcb4f5cdb795c4330d9ecc6b/builtin/providers/aws/resource_aws_alb_test.go#L25-L26

**Comment by sarkis** [comment]
Confirmed this, pushing out a PR shortly

![screen shot 2018-07-20 at 8 03 11 am](https://user-images.githubusercontent.com/42673/43009819-8e0be85a-8bf3-11e8-839f-b01d0682096d.png)
