### ISSUE TITLE
Thresholds defined in seconds should accept a float

### ISSUE THREAD

**Issue by sarkis** [cloudposse/terraform-aws-alb-target-group-cloudwatch-sns-alarms#8]
## what
AWS CloudWatch Alarm Thresholds should be assumed to contain floats when used in conditionals.

## why

Fix the following case:

CloudWatch thresholds are specified in seconds, which results in specifying `500ms` as `0.5` (e.g. for Target Response Time alarm). This will result in an issue when comparing to 0 here:

https://github.com/cloudposse/terraform-aws-alb-target-group-cloudwatch-sns-alarms/blob/master/alarms.tf#L12

example of error:
```
Error: Error asking for user input: 2 error(s) occurred:

* module.default_backend_web_app.module.alb_target_group_alarms.local.TargetResponseTimeAlarmEnabled: local.TargetResponseTimeAlarmEnabled: __builtin_StringToInt: strconv.ParseInt: parsing "0.5": invalid syntax in:

${var.target_response_time_threshold < 0 ? 0 : 1 * local.enabled}
* module.data_model_web_app.module.alb_target_group_alarms.local.TargetResponseTimeAlarmEnabled: local.TargetResponseTimeAlarmEnabled: __builtin_StringToInt: strconv.ParseInt: parsing "0.5": invalid syntax in:

${var.target_response_time_threshold < 0 ? 0 : 1 * local.enabled}
```

**Comment by tamsky** [comment]
Thanks for adding the missing logic to support my changes!

**Comment by sarkis** [comment]
Nw @tamsky was a weird edge case that I luckily already had locally - so immediately caught it 😄 - Thanks again for the support and changes to this module.
